export const regions = [
  "Melbourne CBD",
  "Richmond",
  "Carlton",
  "Southbank",
  "St Kilda",
  "Regional Victoria",
] as const;

export const catalogueCategories = [
  "Beer",
  "Cider",
  "Wine",
  "Spirits",
  "Ready-to-drink",
  "Non-Alcoholic Drinks",
  "Mixers",
  "Barware",
  "Snacks",
  "Premium / Imported",
  "New Arrivals",
] as const;

export const customers = [
  {
    id: "cust-bar-88",
    name: "Bar 88 Melbourne CBD",
    segment: "Craft beer-focused venue",
    region: "Melbourne CBD",
  },
  {
    id: "cust-richmond-bottle",
    name: "Richmond Bottle Shop",
    segment: "High-volume low-margin buyer",
    region: "Richmond",
  },
  {
    id: "cust-northside-hotel",
    name: "Northside Hotel",
    segment: "Seasonal buyer",
    region: "Regional Victoria",
  },
  {
    id: "cust-carlton-wine",
    name: "Carlton Wine Room",
    segment: "Premium wine buyer",
    region: "Carlton",
  },
  {
    id: "cust-chapel-liquor",
    name: "Chapel Street Liquor",
    segment: "Premium spirits buyer",
    region: "St Kilda",
  },
  {
    id: "cust-southbank-events",
    name: "Southbank Events Venue",
    segment: "Fast-growing customer",
    region: "Southbank",
  },
] as const;

const priceTiers = (basePrice: number) => [
  { minCases: 1, price: basePrice },
  { minCases: 6, price: Math.round(basePrice * 0.95) },
  { minCases: 12, price: Math.round(basePrice * 0.9) },
];

export const products = [
  {
    id: "prod-bayline-pale",
    name: "Bayline Session Pale Ale",
    brand: "Harbour Yard Brewing",
    category: "Beer",
    subcategory: "Pale Ale",
    description: "Low-bitterness session pale in a fast-moving carton format for taproom and fridge restocks.",
    imageLabel: "Pale Ale",
    packageSize: "24 x 375ml cans",
    stock: 184,
    regions: ["Melbourne CBD", "Richmond", "Carlton"],
    basePrice: 52,
    quantityPricing: priceTiers(52),
    aiBadges: ["Repeat-order fit", "High venue velocity"],
    similarProductIds: ["prod-ridge-lager", "prod-harbour-ipa"],
  },
  {
    id: "prod-ridge-lager",
    name: "Ridgeway Clean Lager",
    brand: "South Range Brewers",
    category: "Beer",
    subcategory: "Lager",
    description: "Crisp clean lager built for broad venue appeal and predictable weekly replenishment.",
    imageLabel: "Lager",
    packageSize: "24 x 375ml cans",
    stock: 96,
    regions: ["Southbank", "St Kilda", "Regional Victoria"],
    basePrice: 48,
    quantityPricing: priceTiers(48),
    aiBadges: ["Margin steady", "Core range"],
    similarProductIds: ["prod-bayline-pale", "prod-zero-hop"],
  },
  {
    id: "prod-harbour-ipa",
    name: "Harbour Yard Hazy IPA",
    brand: "Harbour Yard Brewing",
    category: "Beer",
    subcategory: "IPA",
    description: "Juicy hazy IPA carton for craft-focused venues rotating higher-margin cans.",
    imageLabel: "IPA",
    packageSize: "16 x 440ml cans",
    stock: 28,
    regions: ["Melbourne CBD", "Richmond", "St Kilda"],
    basePrice: 72,
    quantityPricing: priceTiers(72),
    aiBadges: ["Low-stock watch", "Craft upsell"],
    similarProductIds: ["prod-bayline-pale", "prod-ridge-lager"],
  },
  {
    id: "prod-orchard-cider",
    name: "Ironbark Dry Apple Cider",
    brand: "Field Press Co.",
    category: "Cider",
    subcategory: "Apple Cider",
    description: "Dry apple cider with a clean finish for pub menus and summer fridge sets.",
    imageLabel: "Cider",
    packageSize: "24 x 330ml bottles",
    stock: 74,
    regions: ["Richmond", "Carlton", "Southbank"],
    basePrice: 46,
    quantityPricing: priceTiers(46),
    aiBadges: ["Seasonal mover"],
    similarProductIds: ["prod-pear-cider", "prod-citrus-rtd"],
  },
  {
    id: "prod-pear-cider",
    name: "Meadowrun Pear Cider",
    brand: "Field Press Co.",
    category: "Cider",
    subcategory: "Pear Cider",
    description: "Softer pear cider line for venues needing a sweeter alternative to dry apple.",
    imageLabel: "Pear",
    packageSize: "24 x 330ml bottles",
    stock: 0,
    regions: ["Melbourne CBD", "Carlton"],
    basePrice: 49,
    quantityPricing: priceTiers(49),
    aiBadges: ["Restock requested"],
    similarProductIds: ["prod-orchard-cider", "prod-zero-hop"],
  },
  {
    id: "prod-carlton-pinot",
    name: "Redbrick Lane Pinot Noir",
    brand: "Vale & Row",
    category: "Wine",
    subcategory: "Red Wine",
    description: "Medium-bodied pinot noir suited to bistro glass pours and by-the-bottle lists.",
    imageLabel: "Pinot",
    packageSize: "12 x 750ml bottles",
    stock: 61,
    regions: ["Melbourne CBD", "Carlton", "St Kilda"],
    basePrice: 138,
    quantityPricing: priceTiers(138),
    aiBadges: ["Wine list fit", "Premium margin"],
    similarProductIds: ["prod-new-sauv", "prod-sparkling-trail"],
  },
  {
    id: "prod-sparkling-trail",
    name: "Sparkling Trail Prosecco",
    brand: "Tidal Block",
    category: "Wine",
    subcategory: "Sparkling",
    description: "Bright prosecco carton for events, brunch service, and premium mixer bundles.",
    imageLabel: "Fizz",
    packageSize: "12 x 750ml bottles",
    stock: 112,
    regions: ["Melbourne CBD", "Richmond", "Southbank", "St Kilda"],
    basePrice: 124,
    quantityPricing: priceTiers(124),
    aiBadges: ["Event demand", "Bundle with mixers"],
    similarProductIds: ["prod-new-sauv", "prod-citrus-rtd"],
  },
  {
    id: "prod-juniper-gin",
    name: "Copperstill Coastal Gin",
    brand: "Atlas Stillhouse",
    category: "Spirits",
    subcategory: "Gin",
    description: "Coastal botanical gin for cocktail programs and premium back-bar placement.",
    imageLabel: "Gin",
    packageSize: "6 x 700ml bottles",
    stock: 42,
    regions: ["Melbourne CBD", "Southbank"],
    basePrice: 212,
    quantityPricing: priceTiers(212),
    aiBadges: ["Cocktail menu fit", "Regional constraint"],
    similarProductIds: ["prod-imported-whisky", "prod-tonic"],
  },
  {
    id: "prod-vodka",
    name: "Northbank Triple Vodka",
    brand: "Northbank Spirits",
    category: "Spirits",
    subcategory: "Vodka",
    description: "Neutral triple-distilled vodka for high-volume house pour and event packages.",
    imageLabel: "Vodka",
    packageSize: "6 x 700ml bottles",
    stock: 140,
    regions: ["Melbourne CBD", "Richmond", "Carlton", "Southbank"],
    basePrice: 174,
    quantityPricing: priceTiers(174),
    aiBadges: ["House pour", "Volume discount"],
    similarProductIds: ["prod-juniper-gin", "prod-citrus-rtd"],
  },
  {
    id: "prod-citrus-rtd",
    name: "North Pier Citrus Spritz Cans",
    brand: "North Pier Drinks",
    category: "Ready-to-drink",
    subcategory: "Spritz",
    description: "Citrus spritz cans for faster bar service, events, and outdoor venue fridges.",
    imageLabel: "Spritz",
    packageSize: "24 x 250ml cans",
    stock: 155,
    regions: ["Melbourne CBD", "Richmond", "St Kilda", "Southbank"],
    basePrice: 58,
    quantityPricing: priceTiers(58),
    aiBadges: ["Fast mover", "Event bundle"],
    similarProductIds: ["prod-sparkling-trail", "prod-vodka"],
  },
  {
    id: "prod-cola-rtd",
    name: "Laneway Dark Cola Highball",
    brand: "Laneway Serve",
    category: "Ready-to-drink",
    subcategory: "Highball",
    description: "Dark cola highball cans for late-night venues seeking simple premium serves.",
    imageLabel: "RTD",
    packageSize: "24 x 250ml cans",
    stock: 34,
    regions: ["Richmond", "Carlton", "St Kilda"],
    basePrice: 63,
    quantityPricing: priceTiers(63),
    aiBadges: ["Low-stock watch", "Late-night fit"],
    similarProductIds: ["prod-citrus-rtd", "prod-imported-whisky"],
  },
  {
    id: "prod-zero-hop",
    name: "Clearway Zero Hop Ale",
    brand: "Clearway Brewing",
    category: "Non-Alcoholic Drinks",
    subcategory: "Non-Alcoholic Beer",
    description: "Zero-alcohol hop ale for licensed venues building responsible service ranges.",
    imageLabel: "Zero",
    packageSize: "24 x 330ml cans",
    stock: 133,
    regions: ["Carlton", "Southbank", "Regional Victoria"],
    basePrice: 39,
    quantityPricing: priceTiers(39),
    aiBadges: ["Responsible range", "Growth segment"],
    similarProductIds: ["prod-ridge-lager", "prod-botanical-soda"],
  },
  {
    id: "prod-botanical-soda",
    name: "Gardenline Botanical Soda",
    brand: "Gardenline",
    category: "Non-Alcoholic Drinks",
    subcategory: "Soda",
    description: "Adult botanical soda for no-alcohol pairings and premium table service.",
    imageLabel: "Soda",
    packageSize: "24 x 250ml bottles",
    stock: 58,
    regions: ["Melbourne CBD", "Carlton", "Southbank", "Regional Victoria"],
    basePrice: 35,
    quantityPricing: priceTiers(35),
    aiBadges: ["No-alcohol pair"],
    similarProductIds: ["prod-zero-hop", "prod-tonic"],
  },
  {
    id: "prod-tonic",
    name: "Botanical Dry Tonic 24 Pack",
    brand: "Quarterline Mixers",
    category: "Mixers",
    subcategory: "Tonic",
    description: "Dry tonic carton matched to premium gin service and high-volume cocktail prep.",
    imageLabel: "Tonic",
    packageSize: "24 x 200ml bottles",
    stock: 220,
    regions: ["Melbourne CBD", "Richmond", "Carlton", "Southbank", "St Kilda"],
    basePrice: 31,
    quantityPricing: priceTiers(31),
    aiBadges: ["Bundle with gin", "High stock"],
    similarProductIds: ["prod-juniper-gin", "prod-citrus-mixer"],
  },
  {
    id: "prod-citrus-mixer",
    name: "Citrus Press Mixer Slab",
    brand: "Quarterline Mixers",
    category: "Mixers",
    subcategory: "Citrus Mixer",
    description: "Citrus mixer slab for spritz menus, vodka serves, and event bar packages.",
    imageLabel: "Mixer",
    packageSize: "24 x 200ml bottles",
    stock: 105,
    regions: ["Melbourne CBD", "Richmond", "Southbank"],
    basePrice: 33,
    quantityPricing: priceTiers(33),
    aiBadges: ["Bundle with RTD", "Event prep"],
    similarProductIds: ["prod-tonic", "prod-citrus-rtd"],
  },
  {
    id: "prod-glassware",
    name: "Venue Stemless Tasting Glasses",
    brand: "Service Line",
    category: "Barware",
    subcategory: "Glassware",
    description: "Commercial stemless tasting glasses for wine flights and sampling events.",
    imageLabel: "Glass",
    packageSize: "48 glasses",
    stock: 36,
    regions: ["Melbourne CBD", "Regional Victoria"],
    basePrice: 86,
    quantityPricing: priceTiers(86),
    aiBadges: ["Service add-on"],
    similarProductIds: ["prod-bar-mats", "prod-sparkling-trail"],
  },
  {
    id: "prod-bar-mats",
    name: "Speed Rail Bar Mat Set",
    brand: "Service Line",
    category: "Barware",
    subcategory: "Bar Tools",
    description: "Durable bar mat set for busy rails and fast-clean service stations.",
    imageLabel: "Tools",
    packageSize: "12 mats",
    stock: 24,
    regions: ["Richmond", "Carlton", "Southbank"],
    basePrice: 68,
    quantityPricing: priceTiers(68),
    aiBadges: ["Low-stock watch", "Ops add-on"],
    similarProductIds: ["prod-glassware", "prod-tonic"],
  },
  {
    id: "prod-snacks",
    name: "Salted Kernel Bar Mix Carton",
    brand: "Counter Goods",
    category: "Snacks",
    subcategory: "Bar Snacks",
    description: "Salted snack carton for bar counters, tasting rooms, and quick-margin add-ons.",
    imageLabel: "Snacks",
    packageSize: "36 x 80g packs",
    stock: 88,
    regions: ["Richmond", "Carlton", "St Kilda"],
    basePrice: 44,
    quantityPricing: priceTiers(44),
    aiBadges: ["Counter add-on"],
    similarProductIds: ["prod-pretzel-carton", "prod-orchard-cider"],
  },
  {
    id: "prod-pretzel-carton",
    name: "Pretzel Twist Share Carton",
    brand: "Counter Goods",
    category: "Snacks",
    subcategory: "Share Packs",
    description: "Pretzel share packs for venues that need table snacks with longer shelf life.",
    imageLabel: "Pretzel",
    packageSize: "24 x 150g packs",
    stock: 52,
    regions: ["Melbourne CBD", "Richmond", "St Kilda", "Regional Victoria"],
    basePrice: 47,
    quantityPricing: priceTiers(47),
    aiBadges: ["Shelf stable", "Attach to beer"],
    similarProductIds: ["prod-snacks", "prod-bayline-pale"],
  },
  {
    id: "prod-imported-whisky",
    name: "Kuro Peak Blended Whisky",
    brand: "Kuro Peak",
    category: "Premium / Imported",
    subcategory: "Imported Whisky",
    description: "Imported blended whisky for premium back bars and gifting-season allocations.",
    imageLabel: "Whisky",
    packageSize: "6 x 700ml bottles",
    stock: 18,
    regions: ["Melbourne CBD", "Southbank", "St Kilda"],
    basePrice: 390,
    quantityPricing: priceTiers(390),
    aiBadges: ["Premium allocation", "Low-stock watch"],
    similarProductIds: ["prod-juniper-gin", "prod-imported-tequila"],
  },
  {
    id: "prod-imported-tequila",
    name: "Sierra Azul Reposado Tequila",
    brand: "Sierra Azul",
    category: "Premium / Imported",
    subcategory: "Imported Tequila",
    description: "Reposado tequila allocation for cocktail-led venues and premium bottle displays.",
    imageLabel: "Tequila",
    packageSize: "6 x 700ml bottles",
    stock: 0,
    regions: ["Melbourne CBD", "Richmond", "Southbank"],
    basePrice: 330,
    quantityPricing: priceTiers(330),
    aiBadges: ["Restock requested", "Premium demand"],
    similarProductIds: ["prod-imported-whisky", "prod-citrus-mixer"],
  },
  {
    id: "prod-new-sauv",
    name: "Morning Cut Sauvignon Blanc",
    brand: "Tidal Block",
    category: "New Arrivals",
    subcategory: "New Wine",
    description: "Fresh sauvignon blanc launch line for buyers testing new by-the-glass options.",
    imageLabel: "Sauv",
    packageSize: "12 x 750ml bottles",
    stock: 67,
    regions: ["Melbourne CBD", "Richmond", "Carlton"],
    basePrice: 118,
    quantityPricing: priceTiers(118),
    aiBadges: ["New arrival", "Wine list trial"],
    similarProductIds: ["prod-carlton-pinot", "prod-sparkling-trail"],
  },
  {
    id: "prod-new-aperitif",
    name: "Amber Lane Bitter Aperitif",
    brand: "Amber Lane",
    category: "New Arrivals",
    subcategory: "New Spirits",
    description: "Bitter aperitif launch line for spritz lists, cocktail menus, and seasonal trials.",
    imageLabel: "Aperitif",
    packageSize: "6 x 700ml bottles",
    stock: 31,
    regions: ["Melbourne CBD", "Southbank", "St Kilda"],
    basePrice: 156,
    quantityPricing: priceTiers(156),
    aiBadges: ["New arrival", "Spritz bundle"],
    similarProductIds: ["prod-sparkling-trail", "prod-citrus-mixer"],
  },
] as const;

export const orders = [
  {
    id: "ord-1001",
    customerId: "cust-bar-88",
    date: "2026-04-12",
    status: "Delivered",
    total: 886,
    lines: [
      { productId: "prod-ridge-lager", quantity: 12, unitPrice: 48 },
      { productId: "prod-tonic", quantity: 10, unitPrice: 31 },
    ],
  },
  {
    id: "ord-1002",
    customerId: "cust-bar-88",
    date: "2026-05-11",
    status: "Delivered",
    total: 1512,
    lines: [
      { productId: "prod-bayline-pale", quantity: 18, unitPrice: 52 },
      { productId: "prod-harbour-ipa", quantity: 8, unitPrice: 72 },
    ],
  },
  {
    id: "ord-1003",
    customerId: "cust-bar-88",
    date: "2026-06-09",
    status: "Delivered",
    total: 2874,
    lines: [
      { productId: "prod-bayline-pale", quantity: 24, unitPrice: 52 },
      { productId: "prod-citrus-rtd", quantity: 12, unitPrice: 58 },
      { productId: "prod-tonic", quantity: 30, unitPrice: 31 },
    ],
  },
  {
    id: "ord-2001",
    customerId: "cust-carlton-wine",
    date: "2026-05-20",
    status: "Delivered",
    total: 1656,
    lines: [{ productId: "prod-carlton-pinot", quantity: 12, unitPrice: 138 }],
  },
  {
    id: "ord-2002",
    customerId: "cust-carlton-wine",
    date: "2026-06-18",
    status: "Processing",
    total: 1416,
    lines: [{ productId: "prod-new-sauv", quantity: 12, unitPrice: 118 }],
  },
] as const;

export const inventory = products.map((product) => ({
  productId: product.id,
  onHand: product.stock,
  reorderPoint: product.stock < 50 ? 60 : 90,
}));

export const posSales = [
  { id: "pos-001", customerId: "cust-bar-88", productId: "prod-bayline-pale", weeklyUnits: 6 },
  { id: "pos-002", customerId: "cust-bar-88", productId: "prod-citrus-rtd", weeklyUnits: 5 },
  { id: "pos-003", customerId: "cust-bar-88", productId: "prod-ridge-lager", weeklyUnits: 4 },
  { id: "pos-004", customerId: "cust-bar-88", productId: "prod-harbour-ipa", weeklyUnits: 3 },
  { id: "pos-005", customerId: "cust-bar-88", productId: "prod-tonic", weeklyUnits: 2 },
  { id: "pos-006", customerId: "cust-carlton-wine", productId: "prod-carlton-pinot", weeklyUnits: 3 },
  { id: "pos-007", customerId: "cust-carlton-wine", productId: "prod-new-sauv", weeklyUnits: 2 },
] as const;

export const supportTickets = [
  {
    id: "sup-001",
    customerId: "cust-southbank-events",
    type: "Delivery",
    priority: "Medium",
    status: "Open",
  },
] as const;

export const emailDrafts = [
  {
    id: "email-001",
    customerId: "cust-carlton-wine",
    subject: "Suggested premium wine replenishment",
  },
] as const;

export const workflowLogs = [
  {
    id: "wf-001",
    event: "Weekly report generated",
    status: "Complete",
  },
] as const;

export const locations = regions.map((region) => ({
  region,
  deliveryWindow: region === "Regional Victoria" ? "3-5 business days" : "1-2 business days",
}));

export const mockDataRegistry = {
  customers,
  emailDrafts,
  inventory,
  locations,
  orders,
  posSales,
  products,
  regions,
  supportTickets,
  workflowLogs,
};
